Repository bounswe/2021SpringGroup2, pull requests merged in 2021-06, with the labels that each got.

#71 Equipmentpost class is added.
  practice-app/app/dbinit.py
Labels: Backend, priority: high, state: in progress, state: review needed

#84 Refs #83 - GET blocked user API implemented as described in the linke…
  practice-app/app/block.py
Labels: Backend, priority: high, state: review needed

#79 Added post method for Comment table
  practice-app/app/comment.py
Labels: Backend, priority: high, state: review needed

#63 Event search
  practice-app/app/dbinit.py
  practice-app/app/event.py
Labels: Backend, priority: high, state: review needed

#86 Postspectator
  practice-app/app/player.py
  practice-app/app/spectator.py
Labels: Backend, priority: high, state: review needed

#85 Refs #70 - Merge follow user functionality
  practice-app/app/user.py
Labels: Backend, state: review needed

#93 Changed the route to /api/v1.0/events/<int:post_id>/comments
  practice-app/app/comment.py
Labels: Backend, state: completed, type: enhancement

#82 get comment method added
  practice-app/app/comment.py
Labels: Backend, priority: high, state: review needed

#96 Refs #83 - Corrected the jsonify expression for returning database ob…
  practice-app/app/block.py
Labels: Backend, priority: high, state: review needed

#80 Adjusted GET equipments
  practice-app/app/equipment.py
Labels: Backend, priority: high, state: review needed, type: enhancement

#97 Get comment by id functionality is ready to merge
  practice-app/app/comment.py
Labels: Backend, priority: high, state: review needed

#94 Post users method is created.
  practice-app/app/app.py
  practice-app/app/user.py
Labels: priority: high, state: review needed

#89 Equipment post is modified to use the database.
  practice-app/app/equipment.py
Labels: Backend, state: in progress, state: revision needed

#104 Get notification
  practice-app/app/notification.py
Labels: Backend, priority: high

#107 Refs #59 - Rewrote event post API by communicating with the database.
  practice-app/app/event.py
Labels: Backend, priority: high, state: review needed

#88 Added Post Notification
  practice-app/app/notification.py
Labels: Backend, priority: high, state: review needed

#90 get_user function is added.
  practice-app/app/user.py
Labels: Backend, state: in progress, state: review needed

#103 a simple unit test file is added
  practice-app/test/test.py
Labels: priority: medium, state: completed

#105 Added the unit tests for get comment by id functionality
  practice-app/test/test_get_comment_by_id.py
Labels: Backend, priority: high, state: review needed

#113 Added unit tests for the event search functionality
  practice-app/test/test_event_search.py
Labels: Backend, priority: high, state: review needed

#106 Added unit tests for post comment functionality
  practice-app/test/test_post_comment.py
Labels: Backend, priority: high, state: review needed

#114 Get User Unit Test is Added.
  practice-app/test/test.py
Labels: state: in progress

#118 added unittest for results
  practice-app/test/test.py
Labels: priority: high, state: completed, state: review needed
